name: 05 - Manunal Run with Inputs

on:
  workflow_dispatch:
    inputs:
      evironment:
        description: 'Target evironments'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - dev
          - production
          - uat
          - DR
          - SIT
      version:
        description: 'version to deploy (e.g., 1.4.9)'
        required: false
        default: latest
        type: string
      dry_run:
        description: 'Only simulate, do not actually depoly'
        required: false
        default: true
        type: boolean

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show the inputs the user selected
        run: |
          echo "Environment : ${{ inputs.environment }}"
          echo "Version : ${{ inputs.version }}"
          echo "Dry run? : ${{ inputs.dry_run }}"